### ISSUE TITLE
Throttling Exceptions

### ISSUE THREAD

**Issue by rickwaugh1** [lazywithclass/winston-cloudwatch#31]
I'm trying to understand what would cause these. It seems the default is limit is 5 messages per second, but I saw elsewhere that Winston Cloudwatch only submits once every second. If we only have one server running, or two, we should not running into volume limits, could it be size limits? 

It's a bit confusing the way it works. Looking long term, we are creating an api that could be bombarded with incoming messages, across multiple servers. I'm starting to wonder if CloudWatch itself will let us manage our load.

**Comment by lazywithclass** [comment]
Hey, sorry for the delay, I just moved home.

You got throttled if your action violates either of these conditions: http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/cloudwatch_limits.html

Since that is a limitation on the API side I chose not to code any solution (like queuing) just because it would just grow indefinetely, what you could do, and what Amazon advices you to do, is to have one stream per resource. 
If even with this solution you find your calls to be throttled then I suppose CloudWatch might not be appropriate for your problem.

**Comment by lazywithclass** [comment]
Did you end up using this library?

**Comment by rickwaugh1** [comment]
I moved off the project. Not sure what they are using now.

**Comment by lazywithclass** [comment]
Ok thanks, I'll close this.
