### ISSUE TITLE
Program does not terminate

### ISSUE THREAD

**Issue by alias8** [lazywithclass/winston-cloudwatch#41]
I've tried using the code from the readme. The message does appear in my AWS CloudWatch console, but the program does not terminate. I am using nodejs 6.2.1.

``` javascript
const config = require('./config.json')
const winston = require('winston')
const WinstonCloudWatch = require('winston-cloudwatch')
const moment = require('moment')

winston.add(WinstonCloudWatch, {
  logGroupName: config.cloudWatchLogGroup,
  logStreamName: config.cloudWatchStream,
  awsRegion: config.region
});

winston.info('this is a message sent at ' + moment().format('YYYY-MM-DD-hhmm') + ' from winston-cloudwatch.js');
```

Thanks for any assistance.

**Comment by lazywithclass** [comment]
Hey @alias8, that's the expected behaviour.

Logs are collected into an array and then sent to AWS at a fixed, configurable, rate.
You can see [this behaviour](https://github.com/lazywithclass/winston-cloudwatch/blob/master/index.js#L67) in the code.

**Comment by lazywithclass** [comment]
Does this make sense for you @alias8? Can I consider this closed?

**Comment by alias8** [comment]
Hi @lazywithclass, thanks for the quick response. I didn't realise that was the expected behaviour.

**Comment by lazywithclass** [comment]
No proble @alias8, here's the change, hopefully it will not create doubts in other users :)

https://github.com/lazywithclass/winston-cloudwatch#examples

**Comment by yonahforst** [comment]
I'm trying to use this on AWS lambda but my functions keep timing out, since the process never quits. Any suggestions?

**Comment by lazywithclass** [comment]
@yonahforst Is your requirement to just log once to CloudWatch and then exit?
If so I can extend the library to allow this behaviour.

The process never quits because it needs to send logs to CloudWatch in a timed fashion, to avoid being rejected. This is why I wrapped it in a `setInterval` https://github.com/lazywithclass/winston-cloudwatch/blob/master/index.js#L81.

Let me know, I am happy to cover your scenario.

**Comment by yonahforst** [comment]
@lazywithclass - well, I'm calling `log` multiple times within my lambda function. I really like that it batches them up. But I need someway to terminate the function once all my code has run.

**Comment by lazywithclass** [comment]
@yonahforst Ok let me think about this, I will come back with a proposal.

**Comment by lazywithclass** [comment]
@yonahforst What if I add a handle for `SIGTERM`?

The behaviour would be

```
var winston = require('winston'), WinstonCloudWatch = require('../index');
winston.add(WinstonCloudWatch, { 
  logGroupName: 'testing',
  logStreamName: 'first',
  // ENABLE THE HANDLER
  kthxbye: true
});

winston.error('1');
```

At this point you can either `process.kill(process.pid, 'SIGTERM');` from your code, or `kill $PID` from the console / script on the machine (I know this doesn't apply to you, but it's a nice option for the other people).

What would happen inside winston-cloudwatch is something similar to when we exit because of an `uncaughtException`:

```JS
  clearInterval(this.intervalId);
  this.intervalId = null;
  this.submit(function(/* any args I am missing */) {
    callback();
    process.exit(0);
  });
```

Which basically means "don't do anything anymore, whatever batches you have submit them and then exit."
I could provide a function that is called instead of just `process.exit(0)` if that's too rude.

Or would you rather prefer a function to clear the timeout?

Let me know what you think.

**Comment by yonahforst** [comment]
@lazywithclass - So lambda is kind of weird. They give you a callback, which you call with the result of your code when you finish. When you execute the callback, the process stops and AWS stops billing you. 

I just checked, they don't call `SIGTERM` so maybe a function with a callback would be better

**Comment by lazywithclass** [comment]
@yonahforst You would be the one calling `SIGTERM`, whenever you are done with your work.

**Comment by yonahforst** [comment]
Right but that's not the way I'm supposed to stop a lambda process 😝 I don't the aws police hauling me off in the middle of the night.

**Comment by lazywithclass** [comment]
@yonahforst haha :D Ok, I will have a look at the other method. More on that later on.

**Comment by lazywithclass** [comment]
@yonahforst What about this then, I've quickly coded it and it works, usage:

```JS
var winston = require('winston'),
    WinstonCloudWatch = require('../index');

var self = winston.add(WinstonCloudWatch, {
  logGroupName: 'testing',
  logStreamName: 'first'
});

winston.error('1');

self.transports.CloudWatch.kthxbye(function() {
  console.log('bye');
});
```

`kthxbye` will 

* clear the interval
* submit the logs
* call the callback you provided

and then since there's no more `setInterval` the program will exit.

You need to keep a reference to what I called `self`, so you can get the `WinstonCloudWatch` instance (Winston creates a new transport internally), which is needed to get `intervalId`, so you can `clearTimeout`.

**Comment by yonahforst** [comment]
@lazywithclass  - this looks great! btw i just got `kthxbye` hahhahaha - perfect

**Comment by lazywithclass** [comment]
@yonahforst please have a look at https://github.com/lazywithclass/winston-cloudwatch/pull/53, it should be fine but I could use another pair of eyes.

I will publish 1.9.0 over the weekend.
