### ISSUE TITLE
Move AWS-SDK to peer dependency

### ISSUE THREAD

**Issue by jd-carroll** [lazywithclass/winston-cloudwatch#58]
The AWS-SDK should be specified with a minimum viable version and listed as a `peerDependency` instead of a `dependency`.  This will avoid issues of multiple versions and configuration differences between the versions.

**Comment by lazywithclass** [comment]
Thanks for the info, I will have a look at that. Feel free to submit a PR.

**Comment by polco** [comment]
Actually, would it makes more sense as a dev-dependency since it's only used for testing purpose ? People should not have to download it when requiring the package.

**Comment by DustinWoods** [comment]
This seems old, but I just want to chime in and say I don't think peer dependency makes sense in this case.

**Comment by lazywithclass** [comment]
The point is that I'm not quite sure which is the minimum viable version for aws-sdk, it's been more than 5 years since I used this module, I'm only maintaining it now.
By keeping the version controlled in package.json I'm somewhat controlling it and restricting the number of bugs / issues that can arise.

@jd-carroll if you're not experiencing any particular issue or annoyance I would close this.

**Comment by kevin-king** [comment]
Double posting from a more recent post. Note that `aws-sdk` can be in `devDependencies` (as opposed to `peerDependencies`.

+1

Encountered this on a project. AWS SAM duplicates your lambda NPM modules for every lambda. winston-cloudwatch adds an additional 60 MB per lambda due to the aws-sdk as a regular dependency as @tabroughton described.

This is especially problematic for two reasons (1) it's a logging library, so it's very common that most/every lambda needs winston-cloudwatch (2) it's an issue that scales with your service size. Currently our service is sitting at 17 lambdas and this library causes over 1 GB artifact size (It would be about 20 MB in total otherwise, for reference).

Edit: I also tried using winston-aws-cloudwatch as an alternative library, but it also has aws-sdk independencies.

**Comment by lazywithclass** [comment]
See #144
