### ISSUE TITLE
DataAlreadyAcceptedException

### ISSUE THREAD

**Issue by maxcountryman** [lazywithclass/winston-cloudwatch#59]
I'm seeing this on startup in a Docker container via pm2-docker. It seems like some kind of strange race condition.

**Comment by lazywithclass** [comment]
@maxcountryman Yes it is, I kind of think I know where the problem is, but could you please provide some code showing your problem? You could use [the simulation](https://github.com/lazywithclass/winston-cloudwatch#simulation) to try and reproduce the problem, it would help me understand the problem in your scenario way quicker.

**Comment by maxcountryman** [comment]
Yes it does prevent the logs from being uploaded. I'm not doing anything special, just calling the logger in the callback to starting the Node server.

**Comment by lazywithclass** [comment]
@maxcountryman How many streams are you using in AWS CloudWatch? And how many servers you have with winston-cloudwatch running in them?

When you say

> just calling the logger in the callback to starting the Node server

does that mean that your code looks like this?

```
var winston = require('winston'), WinstonCloudWatch = require('winston-cloudwatch');
winston.add(WinstonCloudWatch, { logGroupName: 'group', logStreamName: 'stream' });

server.listen(port, function() {
  winston.error('1');
});
```

If yes then I really need more info, because this code is working for me.

**Comment by maxcountryman** [comment]
I doubt you'll see this problem unless you're using pm2.

In my case I'm running four/eight processes via pm2-docker.

The sample code you provided is logically equivalent to what I'm doing.

**Comment by lazywithclass** [comment]
@maxcountryman How many streams are you using in AWS CloudWatch?

**Comment by maxcountryman** [comment]
Just a single stream.

**Comment by lazywithclass** [comment]
@maxcountryman [These are AWS CloudWatch limits](http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html), winston-cloudwatch will not synchronise between different processes, as in your case, a solution other people adopted is to [log to different groups / streams](https://github.com/lazywithclass/winston-cloudwatch/blob/master/examples/multiple-loggers.js).

**Comment by maxcountryman** [comment]
That's not the error I'm seeing. It clearly says the batch was already submitted.

**Comment by lazywithclass** [comment]
There's definitely a race condition, and I am suspecting it is because there's just a single stream. [The docs in AWS](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html) about this problem are reduced t the bare minimum.

I will try to come up with an example that reproduces your situation, because without that it's just guess work.

**Comment by maxcountryman** [comment]
Sorry I can't provide more context. When I saw the error I had four processes spun up via pm2-docker and only submitting a single line upon the server starting. In AWS Console I saw three of the expected four lines.

**Comment by lazywithclass** [comment]
That's ok. I've written [the simulation](https://github.com/lazywithclass/winston-cloudwatch#simulation) for these cases, where I can't just come up with an explanation right away. Hopefully I will come back with more context.

**Comment by maxcountryman** [comment]
So what I believe is happening here is when two or more processes are consuming the same stream there is an implicit race condition where processes are competing for use of the `sequenceToken`: essentially what can happen is two or more in-flight requests can contain the same token, especially if they're launched around the same time. One request will win the race and they others will fail with the exception I saw. This request should be retried after obtaining an updated `sequenceToken`.

**Comment by lazywithclass** [comment]
@maxcountryman Sorry for the huge delay, I finally have time to clean issues in this repo.

I am trying to replicate this, because I suspect it's not just happening when someone uses pm2, would this be a correct simulation

```bash
#!/bin/bash

node running-process.js &
node running-process.js &
node running-process.js &
node running-process.js &
```

you could find `running-process.js` here https://github.com/lazywithclass/winston-cloudwatch/blob/master/examples/simulate/running-process.js. Then what I do is take the pids of those processes and feed them to https://github.com/lazywithclass/winston-cloudwatch/blob/master/examples/simulate/log.js.

I always get just one `InvalidSequenceTokenException`, which is expected.

Do you have any hints? It might as well be that the problem now has been fixed, either in winston-cloudwatch, or service side.
