### ISSUE TITLE
"Error: Transport already attached: CloudWatch, assign a different name"?

### ISSUE THREAD

**Issue by ndonnipa** [lazywithclass/winston-cloudwatch#63]
i am using winston-cloudwatch within an AWS lambda function and while the code will work sometimes the other times i get the following error - "Error: Transport already attached: CloudWatch, assign a different name"....below is my code

`var cloudWatchOptions = {
    logGroupName: logGroup,
    logStreamName: stream,
    awsRegion: "region"
  }
  winston.add(require('winston-cloudwatch'), cloudWatchOptions)`

**Comment by lazywithclass** [comment]
It's difficult for me given these informations to tell what's the problem in this case.

Using 

```JavaScript
var winston = require('winston'),
    WinstonCloudWatch = require('../index');


// when you don't provide a name the default one
// is CloudWatch
winston.add(WinstonCloudWatch, {
  logGroupName: 'testing',
  logStreamName: 'first'
});

winston.error('1');
```

which is [in the examples folder](https://github.com/lazywithclass/winston-cloudwatch/tree/master/examples) I am not getting any error. I suspect that you're seeing that error because you're `add`ing the same name multiple times, which is something [winston itself does not allow](https://github.com/winstonjs/winston/blob/master/lib/winston/logger.js#L486), you're seeing "CloudWatch" in the error message because that's the default name I assign if you don't give one.

Hope this helps, let me know if you have any other probems.

**Comment by lazywithclass** [comment]
Do you still have this problem?
