### ISSUE TITLE
Trouble understanding setInterval

### ISSUE THREAD

**Issue by jaimesemp** [lazywithclass/winston-cloudwatch#93]
Hi,

This is not a bug-related but I would like to ask a question.

I really like this logger project (been able to set stream name, and log to several logs at same time is great), but I can't understand the use of a setInterval.

I would like to use in a lambda function, so, I just wanna log and exit.

Would I need to call before exiting my lambda function the referenced code?

```
var winston = require('winston'),
    WinstonCloudWatch = require('../index');

var self = winston.add(WinstonCloudWatch, {
  logGroupName: 'testing',
  logStreamName: 'first'
});

winston.error('1');

self.transports.CloudWatch.kthxbye(function() {
  console.log('bye');
});
```

Why the 'default' behaviour is not just 'log' and exit? I am just a little worried about my 'lambda function' running forever and the bank taking my house 😆 

Thanks in advance

**Comment by jaimesemp** [comment]
I think Im gonna use your 'cousin' winston-aws-cloudwatch plugin.

It does not use setinterval according this: https://github.com/timdp/winston-aws-cloudwatch/issues/50

**Comment by lazywithclass** [comment]
@jaimesemp yes that's a good choice if you're worried about `setInterval`.

The reason why is using `setInterval` is because I wrote this as a quick hack for an internal project in 2014, where I needed it to constantly be there pushing logs... it was the first thing that came to mind, of course it's wrong but it ended up out in the wild and now I am maintaining it :)
